const commonSubjects = ["All", "Bangla", "English", "Math", "Islamic Studies"];
const alimSubjects = [
  "Qur’an Majid & Tajweed",
  "Hadith Sharif",
  "Aqaid & Fiqh",
  "Islamic History",
  "Al-Lughatul Arabiyyatul Ittisaliyyah",
  "Bangla Language",
  "Bangla Literature",
  "English",
  "ICT",
  "Career Education",
  "Physical Education",
  "Health Science & Sports",
  "Physics",
  "Chemistry",
  "Biology",
  "Higher Math",
  "Civics & Citizenship",
  "Islamic Studies",
  "Economics",
  "Logic",
  "Accounting",
  "Business Organization",
  "Finance & Banking",
];

export const filterData = {
  tutoringStyles: [
    "One to One",
    "One to many",
    "Online Tutoring",
    "Shadow Tutoring ",
  ],
  tuitionType: [
    "Home Tutoring",
    "Online Tutoring",
    "Batch Tutoring",
    "Package Tutoring",
    "Coaching Tutoring",
    "Shadow Tutoring"
  ],
  daysPerWeek: [
    "1 Day",
    "2 Days",
    "3 Days",
    "4 Days",
    "5 Days",
    "6 Days",
    "7 Days",
  ],
  cityCorporations: [
    "Dhaka",
    "Savar",
    "Chattogram",
    "Khulna",
    "Rajshahi",
    "Sylhet",
    "Barisal",
    "Rangpur",
    "Cumilla",
    "Gazipur",
    "Narayanganj",
    "Mymensingh",
  ],
  cityCorporationWithLocation: [
    {
      name: "Dhaka",
      locations: [
        "Abdullahpur",
        "Adabor",
        "Aftabnagar",
        "Agargaon",
        "Airport Area ",
        "Amtala",
        "Arambagh",
        "Armanitola",
        "Asad Gate",
        "Ashkona",
        "Azampur Kachabazar",
        "Azimpur",
        "Badda",
        "Baily Road",
        "Bakshi Bazar",
        "Banani",
        "Banani DOHS",
        "Banasree",
        "Bangla Motor",
        "Bangshal",
        "Baridhara",
        "Baridhara DOHS",
        "Bashabo",
        "Bashundhara R/A",
        "Bashundhara Riverview",
        "Baunia",
        "Begun Bari",
        "Bijoy Sarani",
        "Bijoynagar",
        "Bosila",
        "BUET Area",
        "Central Road",
        "Chandrima Model Town",
        "Chawk Bazar",
        "College Gate",
        "Darussalam",
        "Daskhin Khan",
        "Demra",
        "Dhaka  Cantonment",
        "Dhaka Uddan Housing",
        "Dhaka University Area",
        "Dhanmondi",
        "Dholaikhal",
        "Dholaipar",
        "Diabari",
        "Dilkusha",
        "Dilu Road",
        "Doyagonj",
        "Eastern Housing",
        "ECB Chattar",
        "Elephant Road",
        "English Road",
        "Faidabad",
        "Faridabad",
        "Farmgate",
        "Fokirapul",
        "Gabtoli",
        "Gandaria",
        "Golapbag",
        "Gopibagh",
        "Goran",
        "Green Road",
        "Gulistan",
        "Gulshan-1",
        "Gulshan-2",
        "Hatirjheel",
        "Hatirpul",
        "Hazaribag",
        "Ibrahimpur",
        "Indira Road ",
        "Jatrabari",
        "Joynag Road",
        "Jurain ",
        "Kachukhet",
        "Kadamtoli",
        "Kafrul",
        "Kakrail",
        "Kalabagan",
        "Kalachandpur",
        "Kalshi",
        "Kamalapur",
        "Kamarpara",
        "Kamrangirchar",
        "Karwan Bazar",
        "Katabon",
        "Kathal Bagan",
        "Kawla",
        "Kazipara",
        "Kazla",
        "Keraniganj",
        "Khilgaon",
        "Khilkhet",
        "Kollanpur",
        "Kotwali",
        "Kuril",
        "Kurmitola",
        "Lake Circus Road",
        "Lalbag",
        "Lalmatia",
        "Luxmi Bazar",
        "Malibagh",
        "Manikdi",
        "Maniknagar",
        "Matikata",
        "Matuail",
        "Mirpur 1",
        "Mirpur 10",
        "Mirpur 11",
        "Mirpur 12",
        "Mirpur 13",
        "Mirpur 14",
        "Mirpur 2",
        "Mirpur 3",
        "Mirpur 6",
        "Mirpur 7",
        "Mirpur Cantonment",
        "Mirpur DOHS",
        "Mitford Road",
        "Mogbazar",
        "Mohakhali",
        "Mohakhali DOHS",
        "Mohammadpur",
        "Mollartek",
        "Monipur",
        "Monipuri Para",
        "Motijheel",
        "Mouchak",
        "Mugda",
        "Nakhalpara",
        "Nandipara",
        "Narinda",
        "Natun Bazar",
        "Nawabpur",
        "Naya Bazar",
        "Naya Paltan",
        "New Eskaton Road",
        "New Market",
        "Niketon",
        "Nikunja-1",
        "Nikunja-2",
        "Nilkhet",
        "Nobabgonj ",
        "Norda",
        "Paikpara",
        "Pallabi",
        "Paltan",
        "Panthapath",
        "Paribag",
        "Pilkhana",
        "Pink City Model Town",
        "Pirerbag",
        "Postogola",
        "Puran Dhaka",
        "Purana Paltan",
        "Ramna",
        "Rampura",
        "Ranavola",
        "Rayer Bazar",
        "Rayerbag",
        "Razarbagh",
        "Rupnagar",
        "Sabujbag",
        "Sadarghat",
        "Sankar",
        "Sayedabad",
        "Segunbagicha",
        "Shahbag",
        "Shahinbag",
        "Shahjadpur",
        "Shajahanpur",
        "Shantibag",
        "Shantinagar",
        "Shekhertek",
        "Sher-e-Bangla Nagor",
        "Shewra",
        "Shewrapara",
        "Shyamoli",
        "Shyampur",
        "Siddeshwari",
        "Sobahan Bag",
        "Sonir Akra",
        "South Banasree",
        "Sukrabad",
        "Sutrapur",
        "Swamibagh",
        "Tejgaon",
        "Tejkunipara",
        "Tikatuli",
        "Tolarbag",
        "Turag",
        "Uttar Khan",
        "Uttara",
        "Uttara Sector 1",
        "Uttara Sector 2",
        "Uttara Sector 3",
        "Uttara Sector 4",
        "Uttara Sector 5",
        "Uttara Sector 6",
        "Uttara Sector 7",
        "Uttara Sector 8",
        "Uttara Sector 9",
        "Uttara Sector 10",
        "Uttara Sector 11",
        "Uttara Sector 12",
        "Uttara Sector 13",
        "Uttara Sector 14",
        "Uttara Sector 15",
        "Uttara Sector 16",
        "Uttara Sector 17",
        "Uttara Sector 18",
        "Vasantek",
        "Vatara",
        "Wari",
        "West Rampura",
        "Zigatola",
        "Zinzira",
        "Ashulia",
        "Airport",
        "Nikunja 1",
        "Nikunja 2",
        "Bashundhara Residential Area",
        "Gulshan 1",
        "Gulshan 2",
        "Niketan",
        "Dhaka Cantonment Area",
        "North Kafrul",
        "South Kafrul",
        "Nirjhor Residential Area",
        "North Badda",
        "Middle Badda",
        "South Badda",
        "East Badda",
        "Merul Badda",
        "DIT Project",
        "Kalachadpur",
        "Notun Bazar",
        "Meradia",
        "East Rampura",
        "Rampura- Mohanagar Project",
        "Mirpur 9",
        "Senpara Parbata",
        "Shialbari",
        "Sher-E-Bangla Nagar",
        "Rupnagar Residential Area",
        "Banarshi Palli",
        "Kaderabad Housing",
        "Dhaka Uddan",
        "Tajmahal Road",
        "Noorjahan Road",
        "Iqbal Road",
        "Babar Road",
        "Humayun Road",
        "Salimullah Road",
        "Sikder Medical",
        "Beribadh",
        "Geneva Camp",
        "Bijli Moholla",
        "Johuri Moholla",
        "Bashbari",
        "Aziz Moholla",
        "Khilji Road",
        "Ring Road",
        "Mohammadpur Housing Limited",
        "Mohammadia Housing Society",
        "PC Culture Housing",
        "Nobodoy Housing",
        "Chandmiya Housing",
        "West Dhanmondi",
        "Hatirpool",
        "Jigatola",
        "Hazaribagh",
        "Tejturi Bazar",
        "Kawran Bazar",
        "Indira Road",
        "Panthopath",
        "Khamarbari",
        "Monipuripara",
        "East Razabazar",
        "West Razabazar",
        "Shahbagh",
        "DU Area",
        "BUET Campus Area",
        "Palashi",
        "Lalbagh",
        "Komlapur",
        "Moghbazar",
        "Shahjahanpur",
        "Eskaton",
        "Dholai Khal",
        "Islampur",
        "Chawkbazar",
        "Lakshmibazar",
        "Shanir Akhra",
        "Mir Hazaribagh",
        "Rayerbagh",
        "Savar",
        "Dhamrai",
        "Narayanganj",
        "Fatullah",
        "Siddhirganj",
        "Tongi",
        "Gazipur",
        "Kaliakair",
        "Kapasia",
        "Rupganj",
        "Pubail",
        "60 Feet",
      ],
    },
    {
      name: "Savar",
      locations: [
        "Thana Road",
        "20 Mile",
        "Anondopur",
        "Ashuliya",
        "Baipal",
        "Bank Colony",
        "Bank Town",
        "Bazar Road",
        "BEPZA",
        "Birulia Road",
        "C R P Road",
        "Cantonment",
        "Dendabor",
        "DEPZ",
        "Dhamrai",
        "East Bank Town",
        "Genda",
        "Jahangirnagar University Area",
        "Jamgora",
        "Kolma",
        "Majidpur",
        "Mousumi Market",
        "Nayarhat",
        "Nobinagar",
        "Norosinhopur",
        "Palli Bidyut",
        "Radio Colony",
        "Savar Bus Stand",
        "Savar DOHS",
        "Sobhanbag",
        "Soronika R/A",
        "Wapda Road",
        "West Bank Town",
        "Zirabo",
      ],
    },
    {
      name: "Chattogram",
      locations: [
        " New Mooring",
        "2 No. Gate",
        "A.K Khan",
        "Agrabad",
        "Agrabad Access Road",
        "Agrabad Barek Building",
        "Agrabad CDA R/A",
        "Agrabad Chowmuhani",
        "Akbarshah Railway Colony",
        "Ali Nagar",
        "Alkaran ",
        "Aman Bazar",
        "Amirbag",
        "Amtala",
        "Andarkilla",
        "Arakan H/S",
        "Arefin Nagar ",
        "Ashkar Dighir Par",
        "Aturar Depo",
        "Avay Mitra Ghat",
        "Badurtala",
        "Bahaddarhat",
        "Baitush Sharaf",
        "Bakalia East ",
        "Bakalia South",
        "Bakalia West ",
        "Baluchara",
        "Banani R/A",
        "Bandar",
        "Bangladesh Bank Colony",
        "Batali Road ",
        "Battery Goli",
        "Bayazid Bostami",
        "Bepari Para ",
        "Bibirhat",
        "Bondor Tila",
        "Boropool",
        "Bow Bazar",
        "Boxirhat ",
        "Burischar ",
        "Burma Colony",
        "Cantonment ",
        "CDA Residential Area",
        "Cement Crossing",
        "CEPZ",
        "Chaitanna Goli",
        "Chaktai ",
        "Chandgaon",
        "Chandgaon R/A, Block A",
        "Chandgaon R/A, Block B ",
        "Chandrima",
        "Chasma Hill R/A",
        "Chatteswari Road",
        "Chawk Bazar ",
        "Chowdhury Para",
        "Chowmuhani",
        "Cinema Palace ",
        "City Gate",
        "CNB",
        "CNB Colony",
        "Colonel Hat",
        "Cosmopolitan R/A",
        "CRB Road ",
        "D.T. Road ",
        "Dakshin Kattali ",
        "Dampara",
        "Darogha Hat",
        "DC Road ",
        "Debar Par",
        "Dewan Bazar",
        "Dewanhat",
        "Double Mooring ",
        "Enayet Bazar ",
        "Farider Para ",
        "Fatehabad",
        "Firingi Bazar ",
        "Firoz Shah Colony ",
        "Free Port",
        "Gani Colony",
        "GEC Circle",
        "Gol Pahar Moor",
        "Halishahar",
        "Halishahar, Block A",
        "Halishahar, Block B",
        "Halishahar, Block G",
        "Halishahar, Block H",
        "Halishahar, Block I",
        "Halishahar, Block K",
        "Halishahar, Block L",
        "Hamjarbag ",
        "Hashem Bazar",
        "Hathazari",
        "Hazipara ",
        "Hill View R/A",
        "Ice Factory Road ",
        "Ishan Mistrir Hat",
        "Jalalabad H/S",
        "Jamal Khan ",
        "Jangalpara ",
        "Jhawtola",
        "Jubilee Road",
        "Kadamtali  ",
        "Kafco Housing colony",
        "Kalamia Bazar ",
        "Kalurghat",
        "Kamal Gate",
        "Kanon Dhara H/S",
        "Kapasgola",
        "Kaptai Rastar Matha",
        "Kata Pahar Lane",
        "Katalgonj R/A",
        "Kazir Dewri ",
        "Khatiber Hat",
        "Khulshi Colony",
        "Khulshi North",
        "Khulshi South",
        "Khulshi West",
        "Kotwali ",
        "Kulgaon",
        "Kunjachaya R/A",
        "Laldighir Par ",
        "Lalkhan Bazar",
        "Loharpool",
        "Love Lane",
        "M. A Aziz Road",
        "Madarbari East",
        "Madarbari West",
        "Majhir Ghat",
        "Mehedibag",
        "Mistripara",
        "Mohammad Nagar ",
        "Mohammadpur ",
        "Momin Bagh",
        "Momin Road",
        "Monsurabad",
        "Mosjid Goli",
        "Moti Jharna ",
        "Mousumi R/A",
        "Muradpur",
        "Nabi Nagar ",
        "Nalapara ",
        "Nandon Kanon",
        "Nasirabad",
        "Nasirabad H/S",
        "Nazir Para ",
        "Nazu Meah Hat",
        "New Market",
        "North Kattali",
        "O.R. Nizam Road",
        "Oxygen",
        "Pahartali",
        "Panchlaish R/A",
        "Patenga",
        "Pathantuli ",
        "Patharghata ",
        "Polytechnic",
        "Port Colony ",
        "Postarpar",
        "Probortok Circle",
        "Quaish",
        "Rahatarpul",
        "Rahman Nagar ",
        "Rose Valley R/A",
        "Ruby Gate ",
        "Sabujbag",
        "Sadarghat ",
        "Sagorika ",
        "Santibag R/A",
        "Saraipara",
        "Sat Rastar Matha ",
        "Shah Garibullah  H/S",
        "Shamoli R/A",
        "Sheikh Mujib Road",
        "Shershah Colony",
        "Sholokbahar",
        "Sholoshohor",
        "South Kattali",
        "Station Road",
        "Strand Road",
        "Sugandha R/A",
        "Surson Road",
        "Tankey Pahar ",
        "Tiger Pass",
        "Tin Puler Matha",
        "Urdo Road ",
        "Wapda Colony",
        "Zakir Hossain Road",
      ],
    },
    {
      name: "Khulna",
      locations: [
        "PTI More",
        "Toot Para",
        "Alam Nagar",
        "Alutala",
        "Baiti Para",
        "Banargati",
        "Banda",
        "Binoy Para",
        "BL College Area",
        "Bonik Para",
        "Boro Bazar",
        "Boro Khalpar",
        "Bosu Para",
        "Boyra",
        "BSCIC Industrial Area",
        "C&B Colony",
        "Choto Boyra",
        "Choto Khalpar",
        "Christian Colony",
        "Daroga Para",
        "Daspara",
        "Daulatpur",
        "Dharma Shava",
        "District Court",
        "Dokkhin Pabla",
        "Farazi Para",
        "Feri Ghat",
        "Fulbari Gate",
        "Gaikur",
        "Goborchaka",
        "Gollamari",
        "Golokdham",
        "Harinatala",
        "Helatala",
        "Hogladanga Bahsbaria",
        "Horintana",
        "Iqbal Nagar",
        "Islambag",
        "Jhardhanga",
        "Jinnah Para",
        "Jora Gate",
        "Jorakol Bazar",
        "K.D. Ghos Road",
        "Kalibari",
        "Kartik Kul",
        "KDA Avenue",
        "Khalishpur",
        "Khalishpur Bihari Colony",
        "Khan Jahan Ali Road",
        "Kholabaria",
        "Khulna Cantonment",
        "Khulna Medical Area",
        "Khulna University Area",
        "KMP Police Line",
        "Krishna Nagar",
        "KUET Area",
        "Labonchora",
        "Maheswarpasa",
        "Master Para",
        "Mathabhanga",
        "Mia Para",
        "Mirerdanga",
        "Mistri Para",
        "Mohammad Nagar",
        "Munshi Para",
        "Nabinagar",
        "Navi Gate",
        "Nazir Ghat",
        "Nirala Residential Area",
        "Nobo Polli",
        "Notun Rasta",
        "Pabla",
        "Paramanik Para",
        "Poi Para",
        "Poly Technical Area",
        "Rail Station Area",
        "Rasul Bag",
        "Rayer Mahal",
        "Religate",
        "Sanchibunia",
        "Sarkar Para",
        "Sheikh Para",
        "Shib Bari",
        "Shiromoni",
        "Sonadanga",
        "Sonadanga Moylapota",
        "SOS Shishu Polli",
        "Taltola",
        "Taltola Road",
        "Teligati",
        "Textile Mill",
        "Uttor Pabla",
      ],
    },
    {
      name: "Rajshahi",
      locations: [
        "Aam Chattar",
        "Aambagan",
        "Ashrayan Project",
        "Baharampur",
        "Basuri",
        "Binodpur",
        "Bornali Mor",
        "Boro Bongram",
        "Bosepara",
        "Budhpara",
        "Bullanpara",
        "Choto Bongram",
        "Chowddopai",
        "Court Station",
        "Daharampur",
        "Dashmari",
        "Dorga Para",
        "Haragram",
        "Hazrapukur",
        "Horogram",
        "Horogram Notunpara",
        "Kadirganj",
        "Katakhali",
        "Kathalbaria",
        "Kazla",
        "Khojapur",
        "Luxmipur Mor",
        "Meher Chandi ",
        "Methor Para",
        "Mirer Tek",
        "Mollapara",
        "Munshipara",
        "Nagar Para",
        "Nowdapara",
        "Padma Residential Area",
        "Raj Para",
        "Rajshahi University Area",
        "Rani Bazar",
        "Raypara",
        "RUET Area",
        "Sadhur Mor",
        "Sagarpara",
        "Salbagan",
        "Satbaria",
        "Shah Makhdum",
        "Shaheb Bazar",
        "Sheikpara",
        "Shilinda",
        "Shiroil Colony",
        "Sopura",
        "Sufi Nagar",
        "Sultanabad",
        "Terakhadia",
        "Thakurpara",
        "Tikapara",
        "Uposhohor",
        "Vata Para",
      ],
    },
    {
      name: "Sylhet",
      locations: [
        "Akhalia Bazar ",
        "Alampur",
        "Ambarkhana",
        "Badamura",
        "Baghbari",
        "Baluchor",
        "Bandar Bazar ",
        "Bankalapara ",
        "Barudkhana",
        "BGB Camp ",
        "Bhangatikar ",
        "Bhatalia ",
        "Bilpar ",
        "Cantonment",
        "Chalibandar ",
        "Chandmari Tila ",
        "Chowhatta Point ",
        "Chowkidekhi",
        "Daptari Para ",
        "Dariapara ",
        "Daudpur",
        "Dorshon Dewri",
        "Goaitola",
        "Golapbag ",
        "Hazart Shajalal Mazar Sharif ",
        "Hazrat Shah Paran Mazar Sharif",
        "Housing  Estate ",
        "Jail Road",
        "Jalalabad",
        "Jatarpur ",
        "Jharjhari Para ",
        "Kadamtoli ",
        "Kanishail ",
        "Karpara",
        "Kazi Tula",
        "Keya Para  ",
        "Khasdobir",
        "Khuliapara",
        "Khuliatula ",
        "Kolapara",
        "Kotwali ",
        "Kumar Para ",
        "Lakri Para ",
        "Lama Bazar",
        "Lama Para ",
        "Lamapara",
        "Machimpur ",
        "Majon Potti",
        "Majumder Para ",
        "Medical  Road",
        "Mira Bazar ",
        "Mira Para ",
        "Mirer Moydan",
        "Mollapara ",
        "Munshi Para ",
        "Naiorpul",
        "Nayapara",
        "Nayasarak",
        "Nehrai Para ",
        "Nowab Road ",
        "PathanTula",
        "Payra",
        "Police Line",
        "Raynagar",
        "Rikabi Bazar",
        "Sadar Para ",
        "Sadipara ",
        "Saodagar Tola ",
        "Sen Para ",
        "Shagordighirpar",
        "Shahi Eidgah ",
        "Shahjalal Upashahar A Block",
        "Shahjalal Upashahar B Block",
        "Shahjalal Upashahar C Block ",
        "Shahjalal Upashahar D Block ",
        "Shahjalal Upashahar E Block",
        "Shahjalal Upashahar F Block",
        "Shahjalal Upashahar G Block",
        "Shahjalal Upashahar H Block",
        "Shahjalal Upashahar I Block",
        "Shamimabad ",
        "Sheikh para ",
        "Sheikhghat",
        "Shibgonj",
        "Shuna Para",
        "Subhani Ghat",
        "Subid Bazar  ",
        "SUST Area  ",
        "Teli Para",
        "Telihaor ",
        "Tilagor",
        "Uposhohor",
        "West Ghasitula",
        "Western Pir",
        "Zindabazar Point ",
      ],
    },
    {
      name: "Barisal",
      locations: [
        "Barisal Cantonment",
        "30 Godown",
        "Amanotgonj",
        "Amtolar Mor",
        "B.M College Masjid Gate",
        "Baklar Mor",
        "Bales Park",
        "Bazar Road",
        "Beltola",
        "Bibir Pukur Par",
        "Bogura Road",
        "Bot Tola",
        "Brown Compound",
        "Chandmari",
        "Choumatha",
        "Chowk Bazar",
        "College Avenue",
        "Feri Ghat",
        "Folpotti",
        "Gorosthan Road",
        "Hospital Road",
        "Ice Cream Factory Goli",
        "Jail Gate",
        "Jordan Road",
        "Kalizira",
        "Kashipur",
        "Kather Pool",
        "Kawnia",
        "Launch Ghat",
        "Mohabaj",
        "Muktijoddha Park",
        "Munsi Garez",
        "Natullabad",
        "Natun Bazar",
        "Oxford Mission Road",
        "Palashpur",
        "Police Line",
        "Port Road",
        "Ramakrishna Goli",
        "Rupatoli",
        "Rupatoli Housing",
        "Sadar Road",
        "Sagordi",
        "Shadhur Bat Tola",
        "Shoshan Ghat",
        "Sitla Khola",
        "Sonalir Mor",
        "Sreenath Chatterjee Lane",
        "Taltoli",
        "Vatar Khal",
        "Vatikhana",
        "Zero Point",
        "Zia Nagar",
      ],
    },
    {
      name: "Rangpur",
      locations: [
        "Adarsha Para",
        "Alamnagar",
        "Andhar Para",
        "Apon Para",
        "Attia Para",
        "Babu Khan",
        "Bajit Para",
        "Begum Rokeya University Area",
        "Bothla Para",
        "C.O Bazar",
        "Cantonment",
        "Chawak Bazar",
        "Chickli Park",
        "Cicular Road",
        "College Road",
        "Dangi Para",
        "Dewantuli",
        "Dhap",
        "Farm Road",
        "G L Roy Road",
        "Goneshpur",
        "Gunjon More",
        "Gupta Para",
        "Gurati Para",
        "Haffez Para",
        "Haji Para",
        "Haragach",
        "Honuman Tola",
        "Indira Moor",
        "Jolkar Moar",
        "Jumma Para",
        "Kamar Para",
        "Kerani Para",
        "Khorda",
        "Khotkhotia",
        "Koshaituli Road",
        "Kotki Para",
        "Kutir Para",
        "Lalbag",
        "Master Para",
        "Moddho Para",
        "Mulatol",
        "Munshi Para",
        "New Adarsha Para",
        "New Engineer Para",
        "Nilkantho",
        "Pakar Matha Road",
        "Pandar Dighi",
        "Pasari Para",
        "Pashuram",
        "Patbari",
        "Pirgachha",
        "Rahmat Para",
        "Santi Para",
        "Sardar Para",
        "Sen Para",
        "Silmon Road",
        "Sobuj Para",
        "Tajhat Road",
        "Tataipara",
        "Tin Matha",
        "Uttam Bania Para",
        "Uttam Hazi Para",
      ],
    },
    {
      name: "Cumilla",
      locations: [
        "Amtoli",
        "Ashok Tala",
        "Badur Tola",
        "Bagan Bari",
        "Bagichagaon",
        "Baropara",
        "Biswa Road",
        "BSCIC",
        "Chowk bazar",
        "Comilla Export Processing Zone",
        "Court Road",
        "Cumilla Cantonment",
        "Daulatpur",
        "DC Road",
        "Dhanmondi Road",
        "Dharmapur",
        "Dharmasagar Lake",
        "Dhulipara",
        "Digumbaritala",
        "Gobindapur",
        "Housing Estate",
        "Jangalia",
        "Jhakuni Para",
        "Jhautola",
        "Kaliajuri",
        "Kandirpar",
        "Kaptan Bazar",
        "Kotbari",
        "Kuchaituli",
        "Laksham Road",
        "Madina Masjid",
        "Manoharpur",
        "Mughal Toli",
        "Munsef Bari",
        "Nanua Dighir Par",
        "New Market",
        "North Chartha",
        "Nurpur",
        "Police Line",
        "Prince Road",
        "Race Course",
        "Rajgonj",
        "Ramghatla",
        "Ranir Bazar",
        "Ranir Dighir Par",
        "Second Muradpur",
        "Shaktola",
        "Shashongachha",
        "Shatora",
        "South Chartha",
        "Stadium Road",
        "Station Road",
        "Sujanagar",
        "Talpukur Par",
        "Thakur Para",
        "Tomsom Bridge",
        "Town Hall",
        "Ujir Dighirpar",
        "Uttara Residential Area",
        "Victoria College Road",
        "Wapda Colony",
        "Women's College Road",
        "Zilla School Road",
      ],
    },
    {
      name: "Gazipur",
      locations: [
        "B.I.D.C Bazar",
        "Board Bazar",
        "Boro Bari",
        "Boro Dewra",
        "Bypass",
        "Chandona Chowrasta",
        "Cherag Ali Market",
        "College Gate",
        "Dhirasram Bazar",
        "Ershad Nagar",
        "Gazipur Sadar Bazar",
        "Gazipura",
        "Harbaid Bazar",
        "Hossain Market",
        "Joydebpur",
        "Kashimpur Bazar",
        "Kodda Bazar",
        "Konabari Bazar",
        "Majukhan Bazar",
        "Maleker Bari",
        "Meghdubi Bazar",
        "Mil Bazar",
        "Mirer Bazar",
        "Mudafa",
        "National University Area",
        "Pubail Bazar",
        "Pubail College Gate",
        "Rajendrapur",
        "Sataish Bazar",
        "Shalna Bazar",
        "Shib Bari",
        "Shimultali",
        "Sign Board",
        "Station Road",
        "Takshal",
        "Tongi Bazar",
        "Vadun",
      ],
    },
    {
      name: "Narayanganj",
      locations: [
        "02 No. Rail Gate",
        "Amlapara",
        "B.B. Road",
        "Bandar",
        "Borofkol",
        "Burir Dokan",
        "Chanmari",
        "Chashara",
        "Chittagong Road",
        "College Road",
        "Deobhog",
        "DIT Road",
        "Don Chamber",
        "Esa Kha Road",
        "Fatullah",
        "Gabtoli",
        "Godnail",
        "Golachipa",
        "Gymkhana",
        "Jalkuri",
        "Jamtola Road",
        "Kali Bazar",
        "Khanpur",
        "Masdair Gorosthan",
        "Mission Para",
        "Mizmizi",
        "Nitaiganj",
        "Octo Office",
        "Pagla",
        "Paikpara",
        "Pathantuli",
        "Police Line",
        "Ponchoboti",
        "Rupayan Town",
        "Sabujbag",
        "Shahid Bappi Sarani Road",
        "Shitalakshya",
        "Siddhirganj",
        "Signboard",
        "T&T Colony",
        "Tamak Potti",
        "Ukil Para",
      ],
    },
    {
      name: "Mymensingh",
      locations: [
        "Ahammadabad",
        "Akua",
        "Alia Madrasa Road",
        "Amlapara",
        "Baghmara",
        "BAU Area",
        "Biddamoye School Area",
        "Boro Bazar",
        "Boundary Road",
        "Bramopolli",
        "Bypass More",
        "Cantonment",
        "Chamra Godam",
        "Choto Bazar",
        "Dhopakhola",
        "Durgabari",
        "Fulpur",
        "Ganginapar",
        "Golapjan Road",
        "Joynul Abedin Park",
        "Jubilee Road",
        "Kachari",
        "Kachi Jhuli Mor",
        "Kali Bari",
        "Kestopur",
        "Kewatkhali",
        "Lichu Bagan",
        "Maskanda",
        "Mintu College Area",
        "Nahar Road",
        "Natok Gol Lane",
        "Natun Bazar",
        "Naumahal",
        "Pat Godam",
        "Pocha Pukur Par",
        "Police Line",
        "Pondit Para",
        "Rail er Mor",
        "Sankipara",
        "Shehora",
        "Shema Choron Rai Road",
        "Shomvogonj",
        "Stadium Area",
        "Station Road",
        "Taltola",
        "Town Hall Mor",
        "Trishal Bus Stand",
        "Zilla More",
      ],
    },
  ],
  category: [
    "Bangla Medium",
    "English Medium",
    "English Version",
    "Madrasa Medium",
    "Arts",
    "Admission Test",
    "Test Preparation",
    "Religious Studies",
    "Professional Skill Development",
    "Special Skill Development",
    "Language Learning",
    "Uni Help"
    // "Special Child Education",
    // "Uni Help",
  ],
  tutoringCatalog: [
    // English Medium
    {
      id: "english_medium",
      category: "English Medium",
      classes: [
        // ---------- PRE-SCHOOL ----------
        {
          id: "pre_schooling",
          name: "Pre-Schooling",
          subjects: commonSubjects,
        },
        {
          id: "play",
          name: "Play",
          subjects: commonSubjects,
        },
        {
          id: "nursery",
          name: "Nursery",
          subjects: commonSubjects,
        },
        {
          id: "kg",
          name: "KG",
          subjects: commonSubjects,
        },
        {
          id: "kg-1",
          name: "KG-1",
          subjects: commonSubjects,
        },
        {
          id: "kg-2",
          name: "KG-2",
          subjects: commonSubjects,
        },

        // ---------- STANDARD 1 ----------
        {
          id: "standard_1",
          name: "Standard 1",
          subjects: [
            "All",
            "Bangla",
            "English",
            "Maths",
            "Science",
            "Social Studies",
            "ICT",
            "History",
            "Geography",
            "Islamic Studies",
          ],
        },

        // ---------- STANDARD 2 ----------
        {
          id: "standard_2",
          name: "Standard 2",
          subjects: [
            "All",
            "Bangla",
            "English",
            "Maths",
            "Science",
            "Social Studies",
            "ICT",
            "History",
            "Geography",
            "Islamic Studies",
          ],
        },

        // ---------- STANDARD 3 ----------
        {
          id: "standard_3",
          name: "Standard 3",
          subjects: [
            "All",
            "Bangla",
            "English",
            "Maths",
            "Science",
            "Social Studies",
            "ICT",
            "History",
            "Geography",
            "Islamic Studies",
          ],
        },

        // ---------- STANDARD 4 ----------
        {
          id: "standard_4",
          name: "Standard 4",
          subjects: [
            "All",
            "Bangla",
            "English",
            "Math",
            "Science",
            "Social Studies",
            "ICT",
            "History",
            "Geography",
            "Islamic Studies",
            "BGS",
            "Social Science",
          ],
        },

        // ---------- STANDARD 5 ----------
        {
          id: "standard_5",
          name: "Standard 5",
          subjects: [
            "All",
            "Bangla",
            "English",
            "Math",
            "English Literature",
            "Science",
            "Social Studies",
            "ICT",
            "History",
            "Geography",
            "Islamic Studies",
            "BGS",
            "Social Science",
          ],
        },

        // ---------- STANDARD 6 ----------
        {
          id: "standard_6",
          name: "Standard 6",
          subjects: [
            "All",
            "English Language",
            "English Literature",
            "English",
            "Bangla",
            "Math",
            "Math-D",
            "Math-B",
            "Science",
            "Physics",
            "Chemistry",
            "Biology",
            "Bangladesh Studies",
            "Social Science",
            "History",
            "Geography",
            "Bangla Language",
            "Bangla Literature",
            "ICT",
            "Computer Science",
            "Economic",
            "Islamic",
            "Hindu",
            "Buddhist",
            "Christian",
            "Accounting",
            "Business",
            "Languages",
            "Art & Culture",
            "Islamiyat",
          ],
        },

        // ---------- STANDARD 7 ----------
        {
          id: "standard_7",
          name: "Standard 7",
          subjects: [
            "All",
            "English Language",
            "English Literature",
            "English",
            "Bangla",
            "Math",
            "Math-D",
            "Math-B",
            "Science",
            "Physics",
            "Chemistry",
            "Biology",
            "Bangladesh Studies",
            "Social Science",
            "History",
            "Geography",
            "Bangla Language",
            "Bangla Literature",
            "ICT",
            "Computer Science",
            "Economic",
            "Islamic",
            "Hindu",
            "Buddhist",
            "Christian",
            "Accounting",
            "Business",
            "Languages",
            "Art & Culture",
            "Islamiyat",
          ],
        },

        // ---------- STANDARD 8 ----------
        {
          id: "standard_8",
          name: "Standard 8",
          subjects: [
            "All",
            "English Language",
            "English Literature",
            "English",
            "Bangla",
            "Math",
            "Math-D",
            "Math-B",
            "Science",
            "Physics",
            "Chemistry",
            "Biology",
            "Bangladesh Studies",
            "Social Science",
            "History",
            "Geography",
            "Bangla Language",
            "Bangla Literature",
            "ICT",
            "Computer Science",
            "Economic",
            "Islamic",
            "Hindu",
            "Buddhist",
            "Christian",
            "Accounting",
            "Business",
            "Languages",
            "Art & Culture",
            "Islamiyat",
          ],
        },

        // ---------- STANDARD 9 ----------
        {
          id: "standard_9",
          name: "Standard 9",
          subjects: [
            "All",
            "English Language",
            "English Literature",
            "Bangla Languages",
            "Bangla Literature",
            "Math",
            "Add Math",
            "Physics",
            "Chemistry",
            "Biology",
            "Social Science",
            "Science",
            "Accounting",
            "Finance",
            "Management",
            "Marketing",
            "Economics",
            "Business Studies",
            "Geography",
            "History",
            "Sociology",
            "Global Perspectives",
            "Computer Science",
            "ICT",
            "Urdu",
            "Hindi",
            "French",
            "Spanish",
            "Arabic",
            "Chinese",
            "Environmental Management",
            "Islamiyat",
            "Travel & Tourism",
            "Art & Design",
            "Physical Education",
            "Psychology",
            "Genarel Science"
          ],
        },
        // ---------- STANDARD 10 ----------
        {
          id: "standard_10",
          name: "Standard 10",
          subjects: [
            "All",
            "English Language",
            "English Literature",
            "Bangla Languages",
            "Bangla Literature",
            "Math",
            "Add Math",
            "Physics",
            "Chemistry",
            "Biology",
            "Social Science",
            "Science",
            "Accounting",
            "Finance",
            "Management",
            "Marketing",
            "Economics",
            "Business Studies",
            "Geography",
            "History",
            "Sociology",
            "Global Perspectives",
            "Computer Science",
            "ICT",
            "Urdu",
            "Hindi",
            "French",
            "Spanish",
            "Arabic",
            "Chinese",
            "Environmental Management",
            "Islamiyat",
            "Travel & Tourism",
            "Art & Design",
            "Physical Education",
            "Psychology",
            "Genarel Science"
          ],
        },

        // ---------- O LEVEL ----------
        {
          id: "o_level",
          name: "O Level",
          subjects: [
            "All",
            "English Language",
            "English Literature",
            "Bangla Languages",
            "Bangla Literature",
            "Bangla",
            "English",
            "Math",
            "Math D",
            "Add Math",
            "Pure Math",
            "Physics",
            "Chemistry",
            "Biology",
            "Social Science",
            "Science",
            "Accounting",
            "Finance",
            "Management",
            "Marketing",
            "Economics",
            "Business Studies",
            "Geography",
            "History",
            "Sociology",
            "Global Perspectives",
            "Computer Science",
            "ICT",
            "Urdu",
            "Hindi",
            "French",
            "Spanish",
            "Arabic",
            "Chinese",
            "Environmental Management",
            "Islamiyat",
            "Travel & Tourism",
            "Art & Design",
            "Physical Education",
            "Psychology",
          ],
        },

        // ---------- A LEVEL (AS) ----------
        {
          id: "a_level_as",
          name: "A Level (AS)",
          subjects: [
            "English",
            "Bangla",
            "Math",
            "Further Math",
            "Math B",
            "Math D",
            "Statistics",
            "Physics",
            "Chemistry",
            "Biology",
            "Environmental Management",
            "Environmental Systems & Societies",
            "Computer Science",
            "Economics",
            "Business Studies",
            "Business Management",
            "Accounting",
            "Finance",
            "Social Sciences",
            "Psychology",
            "Sociology",
            "Geography",
            "History",
            "Global Perspectives & Research",
            "Global Politics",
            "Politics",
            "English Language",
            "English Literature",
            "Bangla Literature",
            "Bangla Language",
            "French",
            "Spanish",
            "Arabic",
            "Urdu",
            "Chinese",
            "German",
            "Information Technology",
            "Design & Technology",
            "Art & Design",
            "Media Studies",
            "Psychology",
          ],
        },

        // ---------- A LEVEL (A2) ----------
        {
          id: "a_level_a2",
          name: "A Level (A2)",
          subjects: [
            "English",
            "Bangla",
            "Math",
            "Further Math",
            "Math B",
            "Math D",
            "Statistics",
            "Physics",
            "Chemistry",
            "Biology",
            "Environmental Management",
            "Environmental Systems & Societies",
            "Computer Science",
            "Economics",
            "Business Studies",
            "Business Management",
            "Accounting",
            "Finance",
            "Social Sciences",
            "Psychology",
            "Sociology",
            "Geography",
            "History",
            "Global Perspectives & Research",
            "Global Politics",
            "Politics",
            "English Language",
            "English Literature",
            "Bangla Literature",
            "Bangla Language",
            "French",
            "Spanish",
            "Arabic",
            "Urdu",
            "Chinese",
            "German",
            "Information Technology",
            "Design & Technology",
            "Art & Design",
            "Media Studies",
            "Psychology",
          ],
        },
      ],
    },
    // English Version
    {
      id: "english_version",
      category: "English Version",
      classes: [
        // ---------- PRE-SCHOOL ----------
        {
          id: "pre_schooling",
          name: "Pre-Schooling",
          subjects: [
            "All",
            "Bangla",
            "English",
            "Math",
            "Science",
            "Religion",
            "Drawing",
          ],
        },
        {
          id: "play",
          name: "Play",
          subjects: [
            "All",
            "Bangla",
            "English",
            "Math",
            "Science",
            "Religion",
            "Drawing",
          ],
        },
        {
          id: "nursery",
          name: "Nursery",
          subjects: [
            "All",
            "Bangla",
            "English",
            "Math",
            "Science",
            "Religion",
            "Drawing",
          ],
        },
        {
          id: "kg",
          name: "KG",
          subjects: [
            "All",
            "Bangla",
            "English",
            "Math",
            "Science",
            "Religion",
            "Drawing",
          ],
        },
        {
          id: "kg-1",
          name: "KG-1",
          subjects: [
            "All",
            "Bangla",
            "English",
            "Math",
            "Science",
            "Religion",
            "Drawing",
          ]
        },
        {
          id: "kg-2",
          name: "KG-2",
          subjects: [
            "All",
            "Bangla",
            "English",
            "Math",
            "Science",
            "Religion",
            "Drawing",
          ]
        },


        // ---------- PRIMARY (CLASS 1–5) ----------
        {
          id: "class_1",
          name: "Class 1",
          subjects: [
            "All",
            "Bangla",
            "English",
            "Math",
            "Science",
            "Social Studies",
            "Music",
            "Physical Education",
            "Art & Craft",
            "Religious Studies",
          ],
        },
        {
          id: "class_2",
          name: "Class 2",
          subjects: [
            "All",
            "Bangla",
            "English",
            "Math",
            "Science",
            "Social Studies",
            "Music",
            "Physical Education",
            "Art & Craft",
            "Religious Studies",
          ],
        },
        {
          id: "class_3",
          name: "Class 3",
          subjects: [
            "All",
            "Bangla",
            "English",
            "Math",
            "Science",
            "Social Studies",
            "Music",
            "Physical Education",
            "Art & Craft",
            "Religion and Moral Education",
          ],
        },
        {
          id: "class_4",
          name: "Class 4",
          subjects: [
            "All",
            "Bangla",
            "English",
            "Math",
            "Science",
            "Bangladesh & Global Studies",
            "Physical Education & Health",
            "Art & Craft",
            "Religious Studies",
            "Computer Education",
          ],
        },
        {
          id: "class_5",
          name: "Class 5",
          subjects: [
            "All",
            "Bangla",
            "English",
            "Math",
            "Science",
            "Bangladesh & Global Studies",
            "Art & Craft",
            "Religious Studies",
          ],
        },

        // ---------- SECONDARY (CLASS 6–8) ----------
        {
          id: "class_6",
          name: "Class 6",
          subjects: [
            "All",
            "Bangla",
            "Bangla Grammer",
            "English",
            "English Grammer",
            "Math",
            "Science",
            "Bangladesh & Global Science",
            "ICT",
            "Art and Culture",
            "Health Protection",
            "Life and Livelihood",
            "History",
            "Islam",
            "Hindu Religion",
            "Buddhist",
            "Christian",
          ],
        },
        {
          id: "class_7",
          name: "Class 7",
          subjects: [
            "All",
            "Bangla",
            "Bangla Grammer",
            "English",
            "English Grammer",
            "Math",
            "Science",
            "Bangladesh & Global Science",
            "ICT",
            "Art and Culture",
            "Health Protection",
            "Life and Livelihood",
            "History",
            "Islam",
            "Hindu Religion",
            "Buddhist",
            "Christian",
          ],
        },
        {
          id: "class_8",
          name: "Class 8",
          subjects: [
            "All",
            "Bangla",
            "Bangla Grammer",
            "English",
            "English Grammer",
            "Math",
            "Science",
            "Bangladesh & Global Science",
            "ICT",
            "Art and Culture",
            "Health Protection",
            "Life and Livelihood",
            "History",
            "Islam",
            "Hindu Religion",
            "Buddhist",
            "Christian",
          ],
        },

        // ---------- SSC (CLASS 9) ----------
        {
          id: "class_9",
          name: "Class 9",
          subjects: [
            "All",
            "Bangla",
            "English",
            "General Math",
            "Higher Math",
            "Physics",
            "Chemistry",
            "Biology",
            "ICT",
            "Physical Education & Health Science",
            "Bangladesh & Global Science",
            "Islam",
            "Hindu Religion",
            "Buddhist",
            "Christian",
            "Agriculture Studies",
            "Accounting",
            "Finance",
            "Banking",
            "Business Entrepreneurship",
            "General Science",
            "English Grammar and Composition",
            "English For Today",
            "Arts & Crafts",
            "Career Education",
            "Finance & Banking",
            "Economics",
            "Civics & Citizenship",
            "Geography and Environment",
            "History",
            "Bangla Literature",
            "Bangla Grammar",
            "Home Science",
            "General Science",
            "BGS",
            "Business",
            "Science All",
            "Commerce All",
            "Arts All",
          ],
        },
        // ---------- SSC (CLASS 10) ----------
        {
          id: "class_10",
          name: "Class 10",
          subjects: [
            "All",
            "Bangla",
            "English",
            "General Math",
            "Higher Math",
            "Physics",
            "Chemistry",
            "Biology",
            "ICT",
            "Physical Education & Health Science",
            "Bangladesh & Global Science",
            "Islam",
            "Hindu Religion",
            "Buddhist",
            "Christian",
            "Agriculture Studies",
            "Accounting",
            "Finance",
            "Banking",
            "Business Entrepreneurship",
            "General Science",
            "English Grammar and Composition",
            "English For Today",
            "Arts & Crafts",
            "Career Education",
            "Finance & Banking",
            "Economics",
            "Civics & Citizenship",
            "Geography and Environment",
            "History",
            "Bangla Literature",
            "Bangla Grammar",
            "Home Science",
            "General Science",
            "BGS",
            "Business",
            "Science All",
            "Commerce All",
            "Arts All",
          ],
        },
        {
          id: "ssc_candidate",
          name: "SSC Candidate",
          subjects: [
            "All",
            "Bangla",
            "English",
            "General Math",
            "Higher Math",
            "Physics",
            "Chemistry",
            "Biology",
            "ICT",
            "Physical Education & Health Science",
            "Bangladesh & Global Science",
            "Islam",
            "Hindu Religion",
            "Buddhist",
            "Christian",
            "Agriculture Studies",
            "Accounting",
            "Finance",
            "Banking",
            "Business Entrepreneurship",
            "General Science",
            "English Grammar and Composition",
            "English For Today",
            "Arts & Crafts",
            "Career Education",
            "Finance & Banking",
            "Economics",
            "Civics & Citizenship",
            "Geography and Environment",
            "History",
            "Bangla Literature",
            "Bangla Grammar",
            "Home Science",
            "General Science",
            "BGS",
            "Business",
            "Science All",
            "Commerce All",
            "Arts All",
          ],
        },

        // ---------- HSC 1st Year ----------
        {
          id: "hsc_1",
          name: "HSC 1st Year",
          subjects: [
            "All",
            "Bangla",
            "English",
            "ICT",
            "Physics",
            "Chemistry",
            "Biology",
            "Botany",
            "Zoology",
            "Higher Math",
            "Accounting",
            "Business Organization & Management",
            "Finance",
            "Banking & Insurance",
            "Production Management & Marketing",
            "Economics",
            "Agriculture Studies",
            "Geography",
            "Secretarial Science & Office Management",
            "Psychology",
            "Home Science",
            "Statistics",
            "Islamic Studies",
            "Civic & Good Governance",
            "History",
            "Islamic History & Culture",
            "Economics",
            "Logic",
            "Sociology",
            "Social Work",
            "Geography",
            "Marketing",
            "Civics",
            "Accounting",
            "Social Work",
            "Psychology",
          ],
        },
        // ---------- HSC 2nd Year ----------
        {
          id: "hsc_2",
          name: "HSC 2nd Year",
          subjects: [
            "All",
            "Bangla",
            "English",
            "ICT",
            "Physics",
            "Chemistry",
            "Biology",
            "Botany",
            "Zoology",
            "Higher Math",
            "Accounting",
            "Business Organization & Management",
            "Finance",
            "Banking & Insurance",
            "Production Management & Marketing",
            "Economics",
            "Agriculture Studies",
            "Geography",
            "Secretarial Science & Office Management",
            "Psychology",
            "Home Science",
            "Statistics",
            "Islamic Studies",
            "Civic & Good Governance",
            "History",
            "Islamic History & Culture",
            "Economics",
            "Logic",
            "Sociology",
            "Social Work",
            "Geography",
            "Marketing",
            "Civics",
            "Accounting",
            "Social Work",
            "Psychology"
          ],
        },
        {
          id: "hsc_candidate",
          name: "HSC Candidate",
          subjects: [
            "All",
            "Bangla",
            "English",
            "ICT",
            "Physics",
            "Chemistry",
            "Biology",
            "Botany",
            "Zoology",
            "Higher Math",
            "Accounting",
            "Business Organization & Management",
            "Finance",
            "Banking & Insurance",
            "Production Management & Marketing",
            "Economics",
            "Agriculture Studies",
            "Geography",
            "Secretarial Science & Office Management",
            "Psychology",
            "Home Science",
            "Statistics",
            "Islamic Studies",
            "Civic & Good Governance",
            "History",
            "Islamic History & Culture",
            "Economics",
            "Logic",
            "Sociology",
            "Social Work",
            "Geography",
            "Marketing",
            "Civics",
            "Accounting",
            "Social Work",
            "Psychology"
          ],
        },
      ],
    },
    // Bangla Medium
    {
      id: "bangla_medium",
      category: "Bangla Medium",
      classes: [
        {
          id: "pre_schooling",
          name: "Pre-Schooling",
          subjects: [
            "All",
            "Bangla",
            "English",
            "Math",
            "Science",
            "Religion",
            "Drawing",
            "Quran",
            "Spoken",
          ],
        },
        {
          id: "play",
          name: "Play",
          subjects: [
            "All",
            "Bangla",
            "English",
            "Math",
            "Science",
            "Religion",
            "Drawing",
            "Quran",
            "Spoken",
          ],
        },
        {
          id: "nursery",
          name: "Nursery",
          subjects: [
            "All",
            "Bangla",
            "English",
            "Math",
            "Science",
            "Religion",
            "Drawing",
            "Quran",
            "Spoken",
          ],
        },
        {
          id: "kg",
          name: "KG",
          subjects: [
            "All",
            "Bangla",
            "English",
            "Math",
            "Science",
            "Religion",
            "Drawing",
            "Quran",
            "Spoken",
          ],
        },
        {
          id: "kg_1",
          name: "KG-1",
          subjects: [
            "All",
            "Bangla",
            "English",
            "Math",
            "Science",
            "Religion",
            "Drawing",
            "Quran",
            "Spoken",
          ],
        },
        {
          id: "kg_2",
          name: "KG-2",
          subjects: [
            "All",
            "Bangla",
            "English",
            "Math",
            "Science",
            "Religion",
            "Drawing",
            "Quran",
            "Spoken",
          ],
        },
        {
          id: "class_1",
          name: "Class 1",
          subjects: [
            "All",
            "Bangla",
            "English",
            "Math",
            "Science",
            "Social Studies",
            "Music",
            "Physical Education",
            "Drawing",
            "Islam",
            "Quran",
            "Spoken",
          ],
        },
        {
          id: "class_2",
          name: "Class 2",
          subjects: [
            "All",
            "Bangla",
            "English",
            "Math",
            "Science",
            "Social Studies",
            "Music",
            "Physical Education",
            "Drawing",
            "Islam",
            "Quran",
            "Spoken",
          ],
        },
        {
          id: "class_3",
          name: "Class 3",
          subjects: [
            "All",
            "Bangla",
            "English",
            "Math",
            "Science",
            "Social Studies",
            "Music",
            "Physical Education",
            "Drawing",
            "Islam",
            "Quran",
            "Spoken",
          ],
        },
        {
          id: "class_4",
          name: "Class 4",
          subjects: [
            "All",
            "Bangla",
            "English",
            "Math",
            "Science",
            "Social Studies",
            "BGS",
            "ICT",
            "Music",
            "Physical Education",
            "Drawing",
            "Islam",
            "Quran",
            "Spoken",
          ],
        },
        {
          id: "class_5",
          name: "Class 5",
          subjects: [
            "All",
            "Bangla",
            "English",
            "Math",
            "Science",
            "Social Studies",
            "BGS",
            "ICT",
            "Music",
            "Physical Education",
            "Drawing",
            "Islam",
            "Quran",
            "Spoken",
            "Hinduism",
            "Buddhism",
            "Christianity",
          ],
        },
        {
          id: "class_6",
          name: "Class 6",
          subjects: [
            "All",
            "Bangla",
            "English",
            "Math",
            "Science",
            "BGS",
            "Digital Technology",
            "Work and Life-Oriented Education",
            "Physical & Health Education",
            "Fine Arts",
            "Music",
            "Drawing",
            "Quran",
            "Spoken",
            "Islam",
            "Hinduism",
            "Buddhism",
            "Christianity",
          ],
        },
        {
          id: "class_7",
          name: "Class 7",
          subjects: [
            "All",
            "Bangla",
            "English",
            "Math",
            "Science",
            "BGS",
            "Digital Technology",
            "Work & Life-Oriented Education",
            "Physical & Health Education",
            "Arts & Crafts",
            "Agricultural Studies",
            "Islam",
            "Hinduism",
            "Christianity",
            "Buddhism",
            "ICT",
            "Drawing",
            "Quran",
            "Spoken",
          ],
        },
        {
          id: "class_8",
          name: "Class 8",
          subjects: [
            "All",
            "Bangla",
            "English",
            "Math",
            "Science",
            "BGS",
            "Physical & Health Education",
            "Agricultural Studies",
            "Home Science",
            "Islam",
            "Hinduism Studies",
            "Christianity",
            "Buddhism Studies",
            "ICT",
            "Drawing",
            "Quran",
            "Spoken",
          ],
        },
        {
          id: "class_9",
          name: "Class 9",
          subjects: [
            "Bangla",
            "English",
            "ICT",
            "Islam",
            "Hinduism",
            "Buddhism",
            "Christianity",
            "Art",
            "Physics",
            "Chemistry",
            "Biology",
            "General Math",
            "Higher Math",
            "Geography",
            "General Science",
            "BGS",
            "History",
            "Economics",
            "Citizenship & World",
            "Accounting",
            "Finance",
            "Management",
            "Marketing",
            "Drawing",
            "Quran",
            "Spoken",
            "Others",
            "Science All",
            "Commerce All",
            "Arts All",
            "Business"
          ],
        },
        {
          id: "class_10",
          name: "Class 10",
          subjects: [
            "Bangla",
            "English",
            "ICT",
            "Islam",
            "Hinduism",
            "Buddhism",
            "Christianity",
            "Art",
            "Physics",
            "Chemistry",
            "Biology",
            "General Math",
            "Higher Math",
            "Geography",
            "General Science",
            "BGS",
            "History",
            "Economics",
            "Citizenship & World",
            "Accounting",
            "Finance",
            "Management",
            "Marketing",
            "Drawing",
            "Quran",
            "Spoken",
            "Others",
            "Science All",
            "Commerce All",
            "Arts All",
            "Business"
          ],
        },
        {
          id: "ssc_candidate",
          name: "SSC Candidate",
          subjects: [
            "Bangla",
            "English",
            "ICT",
            "Islam",
            "Hinduism",
            "Buddhism",
            "Christianity",
            "Art",
            "Physics",
            "Chemistry",
            "Biology",
            "General Math",
            "Higher Math",
            "Geography",
            "General Science",
            "BGS",
            "History",
            "Economics",
            "Citizenship & World",
            "Accounting",
            "Finance",
            "Management",
            "Marketing",
            "Drawing",
            "Quran",
            "Spoken",
            "Others",
            "Science All",
            "Commerce All",
            "Arts All",
            "Business"
          ],
        },
        {
          id: "hsc_1st_year",
          name: "HSC 1st Year",
          subjects: [
            "Bengali",
            "English",
            "ICT",
            "Physics",
            "Chemistry",
            "Biology",
            "Math",
            "History",
            "Economics",
            "Geography",
            "Logic",
            "Sociology",
            "Islamic Studies",
            "Business Studies",
            "Accounting",
            "Finance",
            "Management",
            "Business Organization & Management",
            "Marketing",
            "Agriculture Studies",
            "Home Science",
            "Civics",
            "Accounting",
            "Social Work",
            "Psychology",
            "Statistics",
          ],
        },
        {
          id: "hsc_2nd_year",
          name: "HSC 2nd Year",
          subjects: [
            "Bengali",
            "English",
            "ICT",
            "Physics",
            "Chemistry",
            "Biology",
            "Math",
            "History",
            "Economics",
            "Geography",
            "Logic",
            "Sociology",
            "Islamic Studies",
            "Business Studies",
            "Accounting",
            "Finance",
            "Management",
            "Business Organization & Management",
            "Marketing",
            "Agriculture Studies",
            "Home Science",
            "Civics",
            "Accounting",
            "Social Work",
            "Psychology",
            "Statistics",
          ],
        },
        {
          id: "hsc_candidate",
          name: "HSC Candidate",
          subjects: [
            "Bengali",
            "English",
            "ICT",
            "Physics",
            "Chemistry",
            "Biology",
            "Math",
            "History",
            "Economics",
            "Geography",
            "Logic",
            "Sociology",
            "Islamic Studies",
            "Business Studies",
            "Accounting",
            "Finance",
            "Management",
            "Business Organization & Management",
            "Marketing",
            "Agriculture Studies",
            "Home Science",
            "Civics",
            "Accounting",
            "Social Work",
            "Psychology",
            "Statistics",
          ],
        },
      ],
    },
    // Madrasa Medium
    {
      id: "madrasa_medium",
      category: "Madrasa Medium",
      classes: [
        // ---------- PRE-SCHOOL ----------
        {
          id: "pre_schooling",
          name: "Pre-Schooling",
          subjects: [
            "All",
            "Bangla",
            "English",
            "Math",
            "Science",
            "Religion",
            "Drawing",
          ],
        },
        {
          id: "play",
          name: "Play",
          subjects: [
            "All",
            "Bangla",
            "English",
            "Math",
            "Science",
            "Religion",
            "Drawing",
          ],
        },
        {
          id: "nursery",
          name: "Nursery",
          subjects: [
            "All",
            "Bangla",
            "English",
            "Math",
            "Science",
            "Religion",
            "Drawing",
          ],
        },
        {
          id: "kg",
          name: "KG",
          subjects: [
            "All",
            "Bangla",
            "English",
            "Math",
            "Science",
            "Religion",
            "Drawing",
          ],
        },

        // ---------- PRIMARY (CLASS 1–5) ----------
        {
          id: "class_1",
          name: "Class 1",
          subjects: [
            "All",
            "Bangla",
            "English",
            "Math",
            "Science",
            "Qur’an Majid & Tajweed",
            "Aqeed & Fiqh",
            "Ad-Durusul Arabia",
          ],
        },
        {
          id: "class_2",
          name: "Class 2",
          subjects: [
            "All",
            "Bangla",
            "English",
            "Math",
            "Science",
            "Qur’an Majid & Tajweed",
            "Aqeed & Fiqh",
            "Ad-Durusul Arabia",
          ],
        },
        {
          id: "class_3",
          name: "Class 3",
          subjects: [
            "All",
            "Bangla",
            "English",
            "Math",
            "Science",
            "Qur’an Majid & Tajweed",
            "Aqeed & Fiqh",
            "Ad-Durusul Arabia",
          ],
        },
        {
          id: "class_4",
          name: "Class 4",
          subjects: [
            "All",
            "Bangla",
            "English",
            "Math",
            "Science",
            "Qur’an Majid & Tajweed",
            "Aqeed & Fiqh",
            "Ad-Durusul Arabia",
          ],
        },
        {
          id: "class_5",
          name: "Class 5",
          subjects: [
            "All",
            "Bangla",
            "English",
            "Math",
            "Science",
            "Bangladesh & Global Studies",
            "Tajweed",
            "Islamic Studies",
            "Arabic",
            "Aqeed & Fiqh",
            "Ad-Durus",
          ],
        },

        // ---------- SECONDARY (CLASS 6–8) ----------
        {
          id: "class_6",
          name: "Class 6",
          subjects: [
            "All",
            "Bangla",
            "English",
            "Math",
            "Science",
            "Social Science",
            "Bangladesh & Global Studies",
            "Qur’an Majid & Tajweed",
            "Al-Aqaed wal Fiqh",
            "Arabic Language & Communication",
            "Arabic Grammar",
            "Ethics & Manners",
            "History of Islam",
            "Hifzul Qur’an",
          ],
        },
        {
          id: "class_7",
          name: "Class 7",
          subjects: [
            "All",
            "Bangla",
            "English",
            "Math",
            "Science",
            "Bangladesh & Global Studies",
            "Qur’an Majid & Tajweed",
            "Al-Aqaid wal Fiqh",
            "Al-Lughatul Arabiyyatul Ittisalia",
            "Qawaidul Lughatil Arabiyyah",
            "Arabic Grammar",
            "Hadith & Munazara",
            "Sirah & Tawhid",
            "ICT",
          ],
        },
        {
          id: "class_8",
          name: "Class 8",
          subjects: [
            "All",
            "Qur’an Majid & Tajweed",
            "Al-Aqaid wal Fiqh",
            "Al-Lughatul Arabiyyatul Irtibat",
            "Qawaidul Lughatil Arabiyyah",
            "Hadith & Sirah",
            "Bangla",
            "English",
            "Math",
            "Science",
            "Bangladesh & Global Studies",
            "ICT",
          ],
        },

        // ---------- SSC (CLASS 9) ----------
        {
          id: "class_9",
          name: "Class 9",
          subjects: [
            "Bangla Literature",
            "Bangla Grammar & Composition",
            "English",
            "English Grammar & Composition",
            "Math",
            "Bangladesh & Global Studies",
            "ICT",
            "Physical Education",
            "Health Science & Sports",
            "Career Education",
            "Physics",
            "Chemistry",
            "Biology",
            "Civics & Citizenship",
            "Home Science",
            "Agricultural Studies",
            "Qur’an Majid & Tajweed",
            "Aqaid & Fiqh",
            "Al-Lughatul Arabiyyatul Ittisaliyyah",
            "Hadith Sharif",
            "Islamic History",
          ],
        },
        // ---------- SSC (CLASS 10) ----------
        {
          id: "class_10",
          name: "Class 10",
          subjects: [
            "Bangla Literature",
            "Bangla Grammar & Composition",
            "English",
            "English Grammar & Composition",
            "Math",
            "Bangladesh & Global Studies",
            "ICT",
            "Physical Education",
            "Health Science & Sports",
            "Career Education",
            "Physics",
            "Chemistry",
            "Biology",
            "Civics & Citizenship",
            "Home Science",
            "Agricultural Studies",
            "Qur’an Majid & Tajweed",
            "Aqaid & Fiqh",
            "Al-Lughatul Arabiyyatul Ittisaliyyah",
            "Hadith Sharif",
            "Islamic History",
          ],
        },

        // ---------- ALIM 1ST YEAR ----------
        {
          id: "alim_1st_year",
          name: "Alim 1st Year",
          subjects: alimSubjects,
        },

        // ---------- ALIM 2ND YEAR ----------
        {
          id: "alim_2nd_year",
          name: "Alim 2nd Year",
          subjects: alimSubjects,
        },
      ],
    },
    // Religious Studies:
    {
      id: "religious_studies",
      category: "Religious Studies",
      classes: [
        // ---------- ISLAMIC STUDIES ----------
        {
          id: "islamic_studies",
          name: "Islamic Studies",
          subjects: [
            "Quran for Beginner",
            "Quran for Adult",
            "Learning Salat",
            "Hifzul Quran",
          ],
        },

        // ---------- HINDUISM STUDIES ----------
        {
          id: "hinduism_studies",
          name: "Hinduism Studies",
          subjects: [
            "Shri Bhagavad Gita for Beginner",
            "Shri Bhagavad Gita for Adult",
          ],
        },

        // ---------- BUDDHISM STUDIES ----------
        {
          id: "buddhism_studies",
          name: "Buddhism Studies",
          subjects: ["Tripitaka for Beginner", "Tripitaka for Adult"],
        },

        // ---------- CHRISTIANITY STUDIES ----------
        {
          id: "christianity_studies",
          name: "Christianity Studies",
          subjects: ["Bible for Beginner", "Bible for Adult"],
        },
      ],
    },
    // Admission Test
    {
      id: "admission_test",
      category: "Admission Test",
      classes: [
        // ---------- PUBLIC UNIVERSITY ----------
        {
          id: "public_university_admission_test",
          name: "Public University Admission Test",
          subjects: [
            "Bangla",
            "English",
            "ICT",
            "Physics",
            "Maths",
            "Chemistry",
            "Biology",
            "Accounting",
            "Management",
            "Marketing",
            "Business Principles",
            "Business Entrepreneurship",
            "Economics",
            "Civics",
            "Analytical Skills",
            "Finance & Banking",
            "General Knowledge",
          ],
        },

        // ---------- PRIVATE UNIVERSITY ----------
        {
          id: "private_university_admission_test",
          name: "Private University Admission Test",
          subjects: [
            "Bangla",
            "English",
            "ICT",
            "Physics",
            "Maths",
            "Chemistry",
            "Biology",
            "Accounting",
            "Management",
            "Analytical Skills",
            "Finance",
            "General Knowledge",
          ],
        },

        // ---------- MEDICAL COLLEGE ----------
        {
          id: "medical_college_admission_test",
          name: "Medical College Admission Test",
          subjects: [
            "English",
            "Physics",
            "Chemistry",
            "Biology",
            "General Knowledge",
          ],
        },

        // ---------- ENGINEERING UNIVERSITY ----------
        {
          id: "engineering_university_admission_test",
          name: "Engineering University Admission Test",
          subjects: [
            "Math",
            "Physics",
            "Chemistry",
            "English",
            "General Knowledge",
          ],
        },

        // ---------- SCHOOL ADMISSION TEST ----------
        {
          id: "school_admission_test",
          name: "School Admission Test",
          subjects: [
            "All",
            "Bangla",
            "English",
            "Maths",
            "General Science",
            "Social Science",
            "Islamic Studies",
            "Geography",
            "General Knowledge",
          ],
        },
      ],
    },
    // Arts
    {
      id: "arts",
      category: "Arts",
      classes: [
        // ---------- DRAWING & PAINTING ----------
        {
          id: "drawing_and_painting",
          name: "Drawing & Painting",
          subjects: ["line Drawing", "Sketch", "Water Color", "Oil Painting"],
        },

        // ---------- HANDWRITING ----------
        {
          id: "handwriting",
          name: "Handwriting",
          subjects: [
            "Bangla Handwriting",
            "English Handwriting",
            "Arabic Handwriting",
            "Chinese Handwriting",
            "korean Handwriting",
            "Russain Handwriting",
            "German Handwriting",
            "French Handwriting",
            "Spanish Handwriting",
          ],
        },

        // ---------- MUSIC ----------
        {
          id: "music",
          name: "Music",
          subjects: [
            "Music for Beginner",
            "Islamic Sangeet",
            "Deshattobodhok Gaan",
            "Folk Sangeet",
            "Nazrul Sangeet",
            "Rabindra Sangeet",
            "Adhunik Sangeet",
            "Uchango Sangeet",
            "Shastriya Sangeet",
            "Polli Giti",
          ],
        },

        // ---------- INSTRUMENTAL MUSIC ----------
        {
          id: "instrumental_music",
          name: "Instrumental Music",
          subjects: [
            "Tabla",
            "Guitar",
            "Harmonium",
            "Ukulele",
            "Clarinet",
            "Silver Flute",
            "Mridanga",
            "Drums",
            "Keyboard",
            "Mandolin",
            "Saxophone",
            "Dotara",
            "Sitar",
            "Flute",
            "Violin",
            "Piano",
            "Behala",
          ],
        },

        // ---------- DANCE ----------
        {
          id: "dance",
          name: "Dance",
          subjects: [
            "Classical Dance",
            "Folk Dance",
            "Modern Dance",
            "Western Dance",
            "Belly Dance",
            "Kathak Dance",
          ],
        },

        // ---------- CRAFTING ----------
        {
          id: "crafting",
          name: "Crafting",
          subjects: [
            "Paper Crafts",
            "Flower Crafts",
            "Fiber & Textile Crafts",
            "Ceramics & Glass Crafts",
            "Needlework",
            "Leather Work",
          ],
        },
      ],
    },
    // Language Learning
    {
      id: "language_learning",
      category: "Language Learning",
      classes: [
        // ---------- ENGLISH ----------
        {
          id: "english_language",
          name: "English",
          subjects: ["English Language learning", "Business Communication"],
        },

        // ---------- ARABIC ----------
        {
          id: "arabic_language",
          name: "Arabic",
          subjects: ["Arabic Language learning"],
        },

        // ---------- JAPANESE ----------
        {
          id: "japanese_language",
          name: "Japanese",
          subjects: ["Japanese Language learning"],
        },

        // ---------- TURKISH ----------
        {
          id: "turkish_language",
          name: "Turkish",
          subjects: ["Turkish Language learning"],
        },

        // ---------- GERMAN ----------
        {
          id: "german_language",
          name: "German",
          subjects: ["German Language learning"],
        },

        // ---------- FRENCH ----------
        {
          id: "french_language",
          name: "French",
          subjects: ["French Language learning"],
        },

        // ---------- SPANISH ----------
        {
          id: "spanish_language",
          name: "Spanish",
          subjects: ["Spanish Language learning"],
        },

        // ---------- CHINESE ----------
        {
          id: "chinese_language",
          name: "Chinese",
          subjects: ["Chinese Language learning"],
        },

        // ---------- KOREAN ----------
        {
          id: "korean_language",
          name: "Korean",
          subjects: ["Korean Language learning"],
        },

        // ---------- BANGLA ----------
        {
          id: "bangla_language",
          name: "Bangla",
          subjects: ["Bangla Language learning"],
        },

        // ---------- RUSSIAN ----------
        {
          id: "russian_language",
          name: "Russian",
          subjects: ["Russian Language learning"],
        },
      ],
    },
    // Test Preparation
    {
      id: "test_preparation",
      category: "Test Preparation",
      classes: [
        // ---------- IELTS ----------
        {
          id: "ielts",
          name: "IELTS",
          subjects: ["Speaking", "Listening", "Reading", "Writing"],
        },

        // ---------- TOEFL ----------
        {
          id: "toefl",
          name: "TOEFL",
          subjects: ["Speaking", "Listening", "Reading", "Writing"],
        },

        // ---------- GMAT ----------
        {
          id: "gmat",
          name: "GMAT",
          subjects: [
            "Analytical Writing Assessment",
            "Integrated Reasoning",
            "Quantitative",
            "Verbal",
          ],
        },

        // ---------- GRE ----------
        {
          id: "gre",
          name: "GRE",
          subjects: [
            "Analytical Writing",
            "Verbal Reasoning",
            "Quantitative Reasoning",
          ],
        },

        // ---------- GED ----------
        {
          id: "ged",
          name: "GED",
          subjects: [
            "Science",
            "Math",
            "Social Studies",
            "Language Writing",
            "Language Reading",
          ],
        },

        // ---------- SAT ----------
        {
          id: "sat",
          name: "SAT",
          subjects: ["Math", "Writing", "Critical Reading"],
        },
      ],
    },
    // Professional Skill Development
    {
      id: "professional_skill_development",
      category: "Professional Skill Development",
      classes: [
        // ---------- WEB DESIGN ----------
        {
          id: "web_design",
          name: "Web Design",
          subjects: [
            "Website Logo",
            "Website Template",
            "Website Banner & Slider",
          ],
        },

        // ---------- WEB DEVELOPMENT ----------
        {
          id: "web_development",
          name: "Web Development",
          subjects: [
            "CSS",
            "HTML",
            "BDMS",
            "CMS",
            "NET",
            "JavaScipt",
            "Python",
            "Perl",
          ],
        },

        // ---------- COMPUTER PROGRAMMING ----------
        {
          id: "computer_programming",
          name: "Computer Programming",
          subjects: [
            "Java",
            "Python",
            "C",
            "C++",
            "React",
            "PHP",
            "Ruby",
            "Matlab",
          ],
        },

        // ---------- ADOBE ILLUSTRATOR ----------
        {
          id: "adobe_illustrator",
          name: "Adobe Illustrator",
          subjects: [
            "Adobe Illustrator in Basic Level",
            "Adobe Illustrator in Advanced Level",
          ],
        },

        // ---------- ADOBE PHOTOSHOP ----------
        {
          id: "adobe_photoshop",
          name: "Adobe Photoshop",
          subjects: [
            "Adobe Photoshop in Basic Level",
            "Adobe Photoshop in Advanced Level",
          ],
        },

        // ---------- MICROSOFT OFFICE ----------
        {
          id: "microsoft_office",
          name: "Microsoft Office",
          subjects: [
            "Microsoft Office Word",
            "Microsoft Office Access",
            "Microsoft Office Excel",
            "Microsoft Office Power Point",
          ],
        },

        // ---------- VIDEO EDITING ----------
        {
          id: "video_editing",
          name: "Video Editing",
          subjects: [
            "Video Editing in Basic Level",
            "Video Editing in Advanced Level",
          ],
        },

        // ---------- FASHION DESIGN ----------
        {
          id: "fashion_design",
          name: "Fashion Design",
          subjects: [
            "Fashion Design in Basic Level",
            "Fashion Design in Advanced Level",
          ],
        },

        // ---------- FASHION DRAWING ----------
        {
          id: "fashion_drawing",
          name: "Fashion Drawing",
          subjects: ["Elements of Design", "Illustration-1", "Illustration-2"],
        },

        // ---------- DIGITAL MARKETING ----------
        {
          id: "digital_marketing",
          name: "Digital Marketing",
          subjects: [
            "Search Engine Optimization (SEO)",
            "Search Engine Marketing (SEM)",
            "Web Analytics",
            "Content Creation",
            "Social Media Marketing (SMM)",
            "Mobile Marketing",
            "Email Marketing",
            "Interactive Marketing",
            "Affiliate Marketing",
          ],
        },

        // ---------- SEWING & TAILORING ----------
        {
          id: "sewing_and_tailoring",
          name: "Sewing & Tailoring",
          subjects: ["Cutting", "Sewing", "Embroidery", "Printmaking"],
        },
      ],
    },
    // Special Skill Development
    {
      id: "special_skill_development",
      category: "Special Skill Development",
      classes: [
        // ---------- PHOTOGRAPHY ----------
        {
          id: "photography",
          name: "Photography",
          subjects: ["Photography Primary Level", "Photography Advanced Level"],
        },

        // ---------- COOKING ----------
        {
          id: "cooking",
          name: "Cooking",
          subjects: [
            "Bangla Food",
            "Thai Food",
            "Chinese Food",
            "Bakery",
            "Pastry",
          ],
        },

        // ---------- YOGA ----------
        {
          id: "yoga",
          name: "Yoga",
          subjects: ["Yoga - Beginner Level", "Yoga - Advanced Level"],
        },

        // ---------- GYM ----------
        {
          id: "gym",
          name: "Gym",
          subjects: ["Gym - Beginner Level", "Gym - Advanced Level"],
        },

        // ---------- DRIVING / RIDING ----------
        {
          id: "driving_riding",
          name: "Driving/ Riding",
          subjects: [
            "Car Driving - Beginner Level",
            "Car Driving - Intermediate Level",
            "Bike Riding - Beginner Level",
            "Bike Riding - Intermediate Level",
            "Scooty Riding - Beginner Level",
            "Scooty Riding - Intermediate Level",
          ],
        },

        // ---------- KARATE ----------
        {
          id: "karate",
          name: "Karate",
          subjects: ["Karate for Beginners", "Karate for Self Defense"],
        },
      ],
    },
  ],
  studentGender: ["male", "female"],
  tutorGender: ["male", "female", "any"],
  placeOfTuition: ["Student's Home", "My Home", "Online"],
  religions: [
    "Islam",
    "Hinduism",
    "Buddhism",
    "Christianity",
    "Indigenous / Tribal Religions",
  ],
};

export const degreeOptions: string[] = [
  "SSC",
  "Dakhil",
  "O Level",
  "HSC",
  "Alim",
  "A Level",
  "Fazil",
  "Kamil",
  "Diploma (Polytechnic)",
  "Honours",
  "Masters",
  "BBA",
  "MBA",
  "BSc",
  "MSc",
  "BA",
  "MA",
  "BSc Engineering",
  "Diploma Engineering",
  "Medical MBBS",
  "Medical BDS",
  "BSS",
  "MSS",
];

export const levelOfEducationOptions: string[] = [
  "Secondary",
  "Higher Secondary",
  "Diploma",
  "Bachelor",
  "Honors",
  "Masters",
  "Doctoral",
];

export const curriculumTypes: string[] = [
  "Bangla Medium",
  "English Version",
  "Cambridge",
  "Ed-Excel",
  "IB",
  "British",
];

export const academicGroups: string[] = [
  "Science",
  "Business Studies",
  "Commerce",
  "Humanities",
  "Arts",
  "Home Economics",
  "Mujabbid",
  "Hifjul Qur’an",
  "Islamic Studies",
];

export const educationBoards: string[] = [
  "Dhaka Board",
  "Chattogram Board",
  "Rajshahi Board",
  "Cumilla Board",
  "Jashore Board",
  "Barisal Board",
  "Sylhet Board",
  "Dinajpur Board",
  "Mymensingh Board",
  "Bangladesh Madrasah Education Board",
  "Bangladesh Technical Education Board",
];

export const departmentsOrSubjects: string[] = [
  "Computer Science & Engineering (CSE)",
  "Software Engineering (SWE)",
  "Information Technology (IT)",
  "Information & Communication Technology (ICT)",
  "Electrical & Electronic Engineering (EEE)",
  "Electronics & Communication Engineering (ECE)",
  "Civil Engineering (CE)",
  "Civil and Environmental Engineering (CEE)",
  "Mechanical Engineering (ME)",
  "Materials & Metallurgical Engineering (MME)",
  "Mechanical and Production Engineering (MPE)",
  "Industrial & Production Engineering (IPE)",
  "Textile Engineering",
  "Chemical Engineering",
  "Mechatronics Engineering",
  "Biomedical Engineering",
  "Architecture",
  "Urban & Regional Planning (URP)",
  "Information & Communication Technology (ICT)",
  "Yarn Engineering (YE)",
  "Fabric Engineering (FE)",
  "Wet Process Engineering (WPE)",
  "Water Resources Engineering (WRE)",
  "Apparel Engineering (AE)",
  "Textile Fashion Design (TFD)",
  "Textile Engineering Management (TEM)",
  "Textile Business Management (TBM)",
  "Textile Machinery Design & Maintenance (TMDM)",
  "Textile Chemical Engineering (TCE)",
  "Technical and Vocational Education (TVE)",
  "Leather Engineering",
  "Footwear Engineering",
  "Leather Products Engineering",
  "Information Technology (IT)",
  "Glass Engineering",
  "Ceramic Engineering",
  "Materials Science & Engineering",
  "Nuclear Engineering",
  "Robotics & Mechatronics Engineering",
  "Industrial & Production Engineering",
  "Energy Engineering",
  "Humanities & Social Sciences (HSS)",
  "Hotel Management",
  "Tourism & Travel Management",
  "Culinary Arts",
  "Welding Technology",
  "Plumbing",
  "Carpentry",
  "Electrical Installation",
  "Machining",
  "Tool & Die Making",
  "Computer Hardware & Networking",
  "Entrepreneurship",
  "Refrigeration & Air Conditioning",
  "Automobile",
  "Automotive Engineering",
  "Food Processing",
  "Graphic Design Multimedia",
  "Fashion Design Apparel Design",
  "Interior Design",
  "Fine Arts",
  "Animation",
  "Mathematics",
  "Applied Mathematics",
  "Physics",
  "Chemistry",
  "Applied Chemistry",
  "Statistics",
  "Environmental Science",
  "Biotechnology",
  "Genetic Engineering",
  "Microbiology",
  "Biochemistry",
  "Molecular Biology",
  "Botany",
  "Zoology",
  "Geology",
  "Geography & Environment",
  "Soil Science",
  "Institute of Education and Research (IER)",
  "Psychology",
  "Oceanography",
  "Forensic Science",
  "Accounting",
  "Finance",
  "Marketing",
  "Management",
  "Human Resource Management (HRM)",
  "Banking & Insurance",
  "International Business",
  "Tourism & Hospitality Management",
  "Supply Chain Management",
  "Management Information Systems (MIS)",
  "Entrepreneurship",
  "Business Administration (BBA / MBA)",
  "Bangla",
  "English",
  "History",
  "Philosophy",
  "Islamic History & Culture",
  "Islamic Studies",
  "Arabic",
  "Persian",
  "Sanskrit",
  "Pali",
  "World Religions & Culture",
  "Fine Arts",
  "Drama & Theatre",
  "Theatre & Performance Studies",
  "Music",
  "Film & Media Studies",
  "Linguistics",
  "Economics",
  "Political Science",
  "Sociology",
  "Anthropology",
  "Public Administration",
  "Social Work",
  "Development Studies",
  "International Relations (IR)",
  "Criminology",
  "Peace & Conflict Studies",
  "Gender Studies",
  "Population Sciences",
  "Human Rights",
  "Medicine (MBBS)",
  "Dental Surgery (BDS)",
  "Pharmacy",
  "Nursing",
  "Public Health",
  "Physiotherapy",
  "Medical Technology",
  "Medical Laboratory Science",
  "Nutrition & Food Science",
  "Radiology & Imaging",
  "Law (LLB)",
  "Law (LLM)",
  "International Law",
  "Criminal Law",
  "Constitutional Law",
  "Education",
  "Educational Psychology",
  "Curriculum & Instruction",
  "Educational Administration",
  "Agriculture",
  "Agronomy",
  "Fisheries",
  "Animal Science",
  "Veterinary Science",
  "Horticulture",
  "Agricultural Engineering",
  "Forestry",
  "Soil Science",
  "Food Technology",
  "Data Science",
  "Artificial Intelligence (AI)",
  "Cyber Security",
  "Game Development",
  "Network Engineering",
  "Mass Communication & Journalism",
  "Media & Communication Studies",
  "Library & Information Science",
  "Islamic Theology",
  "Hadith",
  "Fiqh",
  "Tafsir",
  "Comparative Religion",
  "Disaster Management",
  "Sports Science",
  "Maritime Studies",
  "Aviation Management",
  "Child Development and Social Relationship",
  "Apparel Merchandising and Management (AMA)",
];

export const countries = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cape Verde",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo (Brazzaville)",
  "Congo (Kinshasa)",
  "Costa Rica",
  "Cote d'Ivoire",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "East Timor",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea, North",
  "Korea, South",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macedonia",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Morocco",
  "Mozambique",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia and Montenegro",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Swaziland",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe"
]

export const bangladeshDistricts = [
  "Bagerhat",
  "Bandarban",
  "Barguna",
  "Barishal",
  "Bhola",
  "Bogra",
  "Brahmanbaria",
  "Chandpur",
  "Chapai Nawabganj",
  "Chattogram",
  "Chuadanga",
  "Cox's Bazar",
  "Cumilla",
  "Dhaka",
  "Dinajpur",
  "Faridpur",
  "Feni",
  "Gaibandha",
  "Gazipur",
  "Gopalganj",
  "Habiganj",
  "Jamalpur",
  "Jashore",
  "Jhalokati",
  "Jhenaidah",
  "Joypurhat",
  "Khagrachari",
  "Khulna",
  "Kishoreganj",
  "Kurigram",
  "Kushtia",
  "Lakshmipur",
  "Lalmonirhat",
  "Madaripur",
  "Magura",
  "Manikganj",
  "Meherpur",
  "Moulvibazar",
  "Munshiganj",
  "Mymensingh",
  "Naogaon",
  "Narail",
  "Narayanganj",
  "Narsingdi",
  "Natore",
  "Netrokona",
  "Nilphamari",
  "Noakhali",
  "Pabna",
  "Panchagarh",
  "Patuakhali",
  "Pirojpur",
  "Rajbari",
  "Rajshahi",
  "Rangamati",
  "Rangpur",
  "Satkhira",
  "Shariatpur",
  "Sherpur",
  "Sirajganj",
  "Sunamganj",
  "Sylhet",
  "Tangail",
  "Thakurgaon",
];